CONFIG/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.inventario.urls')),
    path('', include('apps.entidades.urls')),
    path('', include('apps.movimientos.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/inventario/models.py
from datetime import date
from django.db import models
from django.forms import model_to_dict
from django.db.models import Q
from django.utils.formats import date_format

# ubicacion del producto
class Almacen(models.Model):
	nombre = models.CharField(max_length=60, blank=False, null=False)

	class Meta:
		verbose_name = 'Ubicación'
		verbose_name_plural = 'Ubicaciones'

	def __str__(self):
		return f'{self.nombre}'
	
	def toJSON(self):
		item = model_to_dict(self)
		return item
	
# tipo de insumo
class TipoInsumo(models.Model):
	nombre = models.CharField(max_length=60, blank=False, null=False)

	class Meta:
		verbose_name = 'Tipo de insumo'
		verbose_name_plural = 'Tipo de insumos'

	def __str__(self):
		return self.nombre

	def toJSON(self):
		item = model_to_dict(self)
		return item
	
# laboratorio
class Laboratorio(models.Model):
	nombre = models.CharField(max_length=60, blank=False, null=False)

	class Meta:
		verbose_name = 'Laboratorio'
		verbose_name_plural = 'Laboratorios'

	def __str__(self):
		return self.nombre

	def toJSON(self):
		item = model_to_dict(self)
		return item
	
# productos
class Producto(models.Model):

	class Seleccion(models.TextChoices):
		SI = 'SI', 'SÍ'
		NO = 'NO', 'NO'

	nombre = models.CharField(max_length=50, blank=False, null=False)
	almacen = models.ForeignKey(Almacen, verbose_name='Ubicación', on_delete=models.PROTECT, blank=False, null=False)
	tipo_insumo = models.ForeignKey(TipoInsumo, verbose_name='Tipo de insumo', on_delete=models.PROTECT, blank=False, null=False)
	laboratorio = models.ForeignKey(Laboratorio, verbose_name='Laboratorio', on_delete=models.PROTECT, blank=False, null=False)
	if_expire_date = models.CharField(verbose_name='Si caduca', max_length = 2, choices = Seleccion.choices)
	stock_minimo = models.IntegerField(default=0, blank=False, null=False)
	total_stock = models.IntegerField(default=0, null = False, blank= False)
	comprometido = models.IntegerField(default=0, verbose_name='Comprometido')

	def filtrar_inventario_reporte(self):
		filtro = self.inventario.filter(Q(comprometido__gt=0) | Q(stock__gt=0), producto_id=self.pk)
		return filtro

	def contar_productos(self):
		self.total_stock = 0
		self.comprometido = 0
		for s in self.inventario.filter(stock__gt=0):
			self.total_stock += s.stock
		for c in self.inventario.filter(comprometido__gt=0):
			self.comprometido += c.comprometido
		self.save()

	class Meta:
		verbose_name = 'Producto'
		verbose_name_plural = 'Productos'
		ordering = ['nombre']

	def __str__(self):
		return f'{self.nombre}'

	def toJSON(self):
		item = model_to_dict(self)
		item['almacen'] = {'nombre': self.almacen.nombre, 'id': self.almacen.pk}
		item['laboratorio'] = {'nombre':self.laboratorio.nombre, 'id': self.laboratorio.pk}
		item['tipo_insumo'] = {'nombre': self.tipo_insumo.nombre, 'id': self.tipo_insumo.pk}
		return item

class Inventario(models.Model):
	lote = models.CharField(max_length=50,verbose_name='Codigo de lote')
	f_vencimiento = models.DateField(auto_now=False, auto_now_add=False, verbose_name='Fecha de vencimiento')
	stock = models.IntegerField(default=0, verbose_name='Stock')
	comprometido = models.IntegerField(default=0, verbose_name='Comprometido')
	producto = models.ForeignKey(Producto, on_delete=models.CASCADE, related_name='inventario', verbose_name='Producto')

	class Meta:
		verbose_name = 'Inventario'
		verbose_name_plural = 'Inventarios'
		# permissions = [
		# 	("can_view_student", "Can view student"),
		# ]

	def __str__(self):
		return "{} - {}".format(self.producto.nombre, self.lote)

	def toJSON(self):
		item = model_to_dict(self)
		item['nombre'] = self.producto.nombre
		item['fecha_vencimiento'] = date_format(self.f_vencimiento, "d/m/Y")
		item['cantidad_contada'] = 0
		return item

templates/pages/productos/detalle_producto.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}
    Detalle del producto
{% endblock title %}

{% block extra_css %}    	
    <!--Data table-->
    <link rel="stylesheet" href="{% static 'css/buttons.bootstrap5.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/dataTables.bootstrap5.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.bootstrap5.min.css' %}">
{% endblock extra_css %}

{% block body %}
    <div class="row">
        <div class="col col-md-12">
            <div class="card">
                <div class="card-header">
                    <strong class="card-title">{{sub_title}}</strong>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col col-md-3">
                            <h4 class="card-title">ID</h4>
                            <p class="card-text">{{ producto.pk }}.</p>
        
                        </div>
                        <div class="col col-md-3">
                            <h4 class="card-title">Nombre</h4>
                            <p class="card-text">{{producto.nombre}}.</p>
        
                        </div>
                        <div class="col col-md-3">
                            <h4 class="card-title">Almacen</h4>
                            <p class="card-text">{{ producto.almacen }}.</p>
                        </div>
                        <div class="col col-md-3">
                            <h4 class="card-title">Laboratorio</h4>
                            <p class="card-text">{{ producto.laboratorio }}.</p>
                        </div>
                    </div>
                    <div class="row mt-4">
                        <div class="col col-md-3">
                            <h4 class="card-title">Tipo de insumo</h4>
                            <p class="card-text">{{ producto.tipo_insumo }}.</p>
                        </div>
                        <div class="col col-md-3">
                            <h4 class="card-title">Caduca?</h4>
                            <p class="card-text">{{ producto.if_expire_date|yesno:'Si,No' }}.</p>
                        </div>
                        <div class="col col-md-3">
                            <h4 class="card-title">Stock minimo</h4>
                            <p class="card-text">{{ producto.stock_minimo }}.</p>
                        </div>
                        <div class="col col-md-3">
                            <h4 class="card-title">Stock Total </h4>
                            <p class="card-text">{{ producto.total_stock }}.</p>
                        </div>
                    </div>
                    <div class="row mt-4">
                        <div class="col col-md-3">
                            <h4 class="card-title">Comprometido </h4>
                            <p class="card-text">{{ producto.comprometido }}.</p>
                        </div>
                    </div>
    
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col col-md-12">
            <div class="card">
                <div class="card-header">
                    <strong class="card-title">Inventario</strong>
                </div>
                <div class="card-body">
                    <div class="dt-responsive table-responsive">
                        <table id="listado" class="table table-striped table-hover table-bordered nowrap">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Lote</th>
                                    <th>Fecha Vencimiento</th>
                                    <th>Stock</th>
                                    <th>Comprometido</th>
                                  </tr>
                            </thead>
                            <tbody>         
                                    {% for i in inventario %}
                                        <tr>
                                            <td>{{ i.pk }}</td>
                                            <td>{{ i.lote }}</td>
                                            <td>{{ i.f_vencimiento|date:'d/m/Y' }}</td>
                                            <td>{{ i.stock }}</td>
                                            <td>{{ i.comprometido }}</td>
                                        </tr>
                                    {% endfor %}                                    
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col col-md-12">
            <div class="card">
                <div class="card-header">
                    <strong class="card-title">Historial de movimientos</strong>
                </div>
                <div class="card-body">
                    <div class="dt-responsive table-responsive">
                        <table id="listado2" class="table table-striped table-hover table-bordered nowrap">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Tipo de movimiento</th>
                                    <th>Fecha</th>
                                    <th>Empleado</th>
                                    <th>Producto-Lote</th>
                                    <th>Cantidad</th>
                                  </tr>
                            </thead>
                            <tbody>         
                                    {% for h in historial %}
                                        <tr>
                                            <td>{{ h.pk }}</td>
                                            <td>{{ h.tipo_mov.nombre }}</td>
                                            <td>{{ h.fecha_mov|date:'d/m/Y' }}</td>
                                            <td>
                                                {% if h.tipo_mov.nombre == 'PACIENTE NO RETIRO SOLICITUD DE MEDICAMENTOS' %}
                                                    SISTEMA
                                                {% else %}
                                                    {{ h.empleado.nombres }} {{ h.empleado.apellidos }}                                              
                                                {% endif %}
                                            </td>
                                            <td>{{ h.producto.producto }} - {{ h.producto.lote }}</td>
                                            
                                            {% if h.tipo_mov.operacion == '+' %}
                                                <td><span class="badge badge-success">+{{ h.cantidad }}</span></td>
                                            {% elif h.tipo_mov.operacion == '-' %}
                                                <td><span class="badge badge-danger">-{{ h.cantidad }}</span></td>
                                            {% elif h.tipo_mov.operacion == '=' %}
                                                <td><span class="badge badge-dark">{{ h.cantidad }}</span></td>
                                            {% endif %}
                                                
                                        </tr>
                                    {% endfor %}                                    
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock body %}

{% block extrajs %}
	<!--Data table-->
	<script src="{% static 'js/plugins/jquery.dataTables.min.js' %}"></script>
	<script src="{% static 'js/plugins/dataTables.bootstrap5.min.js' %}"></script>
	<script src="{% static 'js/plugins/dataTables.responsive.min.js' %}"></script>
	<script src="{% static 'js/plugins/responsive.bootstrap5.min.js' %}"></script>     

    <script>
        /** OPEN MODAL PRODUCT **/
        $('a[rel="ver_recipe"]').on('click', function () {
            $('#modal_recipe').modal('show');
        });

        $('#listado2').DataTable({
            responsive: true,
            autoWidth: false,
            destroy: true,
            deferRender: true,
            ordering: false,
            searching: true,
            paging: true,
            "language": {
                "sProcessing": "Procesando...",
                "sLengthMenu": "Mostrar _MENU_ registros",
                "sZeroRecords": "No se encontraron resultados",
                "sEmptyTable": "Ningún dato disponible en esta tabla",
                "sInfo": "Mostrando del _START_ al _END_ de un total de _TOTAL_ registros",
                "sInfoEmpty": "Mostrand del 0 al 0 de un total de 0 registros",
                "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                "sInfoPostFix": "",
                "sSearch": "Buscar:",
                "sUrl": "",
                "sInfoThousands": ",",
                "sLoadingRecords": "Cargando...",
                "oPaginate": {
                    "sFirst": "<span class='fa fa-angle-double-left'></span>",
                    "sLast": "<span class='fa fa-angle-double-right'></span>",
                    "sNext": "<span class='fa fa-angle-right'></span>",
                    "sPrevious": "<span class='fa fa-angle-left'></span>"
                },
                "oAria": {
                    "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                    "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                }
            },
            initComplete: function(settings, json) {
        
            }
	    });
    </script>

{% endblock extrajs %}

templates/pages/productos/listado_productos.html
{% extends 'base/base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}
    Listado de productos
{% endblock title %}

{% block extra_css %}
    	<!--Data table-->
	<link rel="stylesheet" href="{% static 'css/buttons.bootstrap5.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/dataTables.bootstrap5.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/responsive.bootstrap5.min.css' %}">
{% endblock extra_css %}

{% block body %}
<div class="row">
    <!-- Zero config table start -->
    <div class="col-sm-12">
        <div class="card">
            <div class="card-header d-flex align-items-center justify-content-between">
                <h5 id="page_title">{{ sub_title }}</h5>
                <div class="cart-tools">
                    <!-- <a href="#" id="btn_filter" class="btn btn-icon btn-light-dark ml-10" rel="btn_open_modal_report" data-bs-toggle="tooltip" data-bs-placement="top" title="Reportes">
                        <i class="fas fa-file-pdf"></i>
                    </a> -->
                    <a href="#" class="btn btn-icon btn-info" data-bs-toggle="tooltip" title="Registrar producto" id="btn_nuevo_producto">
                        <i class="fa fa-plus text-white"></i>
                    </a>
                </div>
            </div>
            <div class="card-body">
                {% if messages %}
                    {% for message in messages %}
                        <div class="sufee-alert alert with-close alert-success alert-dismissible fade show">
                            <span class="badge badge-pill badge-success">Exito!</span>
                            {{ message }}.
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">×</span>
                            </button>
                        </div>
                    {% endfor %}
                {% endif %}
                <div class="dt-responsive table-responsive">
                    <table id="listado_productos" class="table table-striped table-hover table-bordered nowrap">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Nombre</th>
                                <th>Almacen</th>
                                <th>Laboratorio</th>
                                <th>Total Stock</th>
                                <th>Comprometido</th>
                                <th>Opciones</th>
                              </tr>
                        </thead>
                        <tbody>
                        </tbody>
                        <tfoot>
                            <tr>
                                <th>ID</th>
                                <th>Nombre</th>
                                <th>Almacen</th>
                                <th>Laboratorio</th>
                                <th>Total Stock</th>
                                <th>Comprometido</th>
                                <th>Opciones</th>
                            </tr>
                        </tfoot>
                    </table>
                        
                </div>
            </div>
        </div>
    </div>
    <!-- Zero config table end -->
</div>

<!-- modales -->
<div class="modal fade" id="smallmodal" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="smallmodalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <form method="post" id="form_producto">{% csrf_token %}
            <input type="hidden" name="action" id="action" value="">
            <input type="hidden" name="id" id="" value="">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="titulo_modal"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="modal-body">
                        <div class="row g-2 mb-3">
                            <div class="col">
                                <label for="id_nombre">Nombre del producto</label>
                                {{form.nombre|add_class:'form-control'|attr:'onkeypress:return Texto_Numeros(event)'}}
                            </div>
                            <div class="col">
                                <label for="id_almacen">Almacen</label>
                                {{form.almacen|add_class:'form-control'|attr:'type:select'}}
                            </div>
                        </div>
                        <div class="row g-2 mb-3">
                            <div class="col">
                                <label for="id_tipo_insumo">Tipo de insumo</label>
                                {{form.tipo_insumo|add_class:'form-control'|attr:'type:select'}}
                            </div>
                            <div class="col">
                                <label for="id_laboratorio">Laboratorio</label>
                                {{form.laboratorio|add_class:'form-control'|attr:'type:select'}}
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col">
                                <label for="id_if_expire_date">¿Se vence?</label>
                                {{form.if_expire_date|add_class:'form-control'|attr:'type:select'}}
                            </div>
                            <div class="col">
                                <label for="id_stock_minimo">Stock minimo</label>
                                {{form.stock_minimo|add_class:'form-control'}}
                            </div>
                            <div class="col">
                                <label for="id_total_stock">Stock Total</label>
                                {{form.total_stock|add_class:'form-control'|attr:'readonly'}}
                            </div>
                            <div class="col">
                                <label for="id_comprometido">Comprometido</label>
                                {{form.comprometido|add_class:'form-control'|attr:'readonly'}}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-primary">Confirmar</button>
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock body %}


{% block extrajs %}
    <!--Data table-->
    <script src="{% static 'js/plugins/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'js/plugins/dataTables.bootstrap5.min.js' %}"></script>
    <script src="{% static 'js/plugins/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'js/plugins/responsive.bootstrap5.min.js' %}"></script>
    <script src="{% static 'js/pages/inventario/productos.js' %}"></script>
{% endblock extrajs %}
    