CONFIG/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.inventario.urls')),
    path('', include('apps.entidades.urls')),
    path('', include('apps.movimientos.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/entidades/models.py
from django.db import models
from django.forms import model_to_dict
from django.contrib.auth.models import User

# zona
class Zona(models.Model):
	zona_residencia = models.CharField(max_length=60, blank=False, null=False)

	class Meta:
		verbose_name = 'Zona'
		verbose_name_plural = 'Zonas'

	def __str__(self):
		return self.zona_residencia

	def toJSON(self):
		item = model_to_dict(self)
		return item

class Persona(models.Model):

	class Genero(models.TextChoices):
		MASCULINO = 'MA', 'Masculino'
		FEMENINO = 'FE', 'Femenino'

	class Nacionalidad(models.TextChoices):
		VENEZOLANO = 'V-', 'V-'
		EXTRANJERO = 'E-', 'E-'
		JURIDICO = 'J-', 'J-'
	
	class CodigoTlf(models.TextChoices):
		C412 = '0412', '0412'
		C414 = '0414', '0414'
		C416 = '0416', '0416'
		C424 = '0424', '0424'
		C426 = '0426', '0426'

	nacionalidad = models.CharField(max_length=2, choices=Nacionalidad.choices, default=Nacionalidad.VENEZOLANO, blank=False, null=False)
	cedula = models.CharField(max_length=8, blank=False, null=False)
	nombres = models.CharField(max_length=50, blank=False, null=False)
	apellidos = models.CharField(max_length=50, blank=False, null=False)
	telefono = models.CharField(max_length=11, blank=True, null=True)
	genero = models.CharField(max_length=2, blank=False, null=False, choices=Genero.choices)
	f_nacimiento = models.DateField(auto_now_add = False, auto_now=False, blank=False, null=False)
	embarazada = models.BooleanField(blank=False, null=False)
	c_residencia = models.FileField(upload_to='constancias_residencias/', blank=True, null=True)
	zona  = models.ForeignKey(Zona, on_delete=models.PROTECT, blank=False, null=False)
	direccion = models.TextField(blank=False, null=False)
	patologia = models.TextField(blank=True, null=True)

	class Meta:
		abstract = True

	def toJSON(self):
		item = model_to_dict(self)
		if self.c_residencia:
			item['c_residencia'] = self.c_residencia.url
		else:
			item['c_residencia'] = None
		return item

class Perfil(Persona):
	class Rol(models.TextChoices):
		ADMINISTRADOR = 'AD', 'Administrador'
		ALMACENISTA = 'AL', 'Almacenista'
		AT_CLIENTE = 'AT', 'Atención al Cliente'
		JEFE_COMUNIDAD = 'JC', 'Jefe de Comunidad'
		PACIENTE = 'PA', 'Paciente'
	
	rol = models.CharField(max_length=2, choices=Rol.choices, default=Rol.PACIENTE)
	usuario = models.OneToOneField(User, on_delete=models.CASCADE, related_name='perfil')
	
	def __str__(self):
		return f'{self.cedula}-{self.nombres}'
	
	class Meta:
		verbose_name = 'perfil'
		verbose_name_plural = 'perfiles'
		permissions = [
			('cambiar_password', 'cambiar contraseña a usuarios'),
			('respaldar_db', 'Respaldar Base de datos'),
			('recuperar_db', 'Recuperar Base de datos'),
			('cambiar_estado_usuarios', 'cambiar estado de usuarios'),
			('cambiar_estado_jornada', 'cambiar estatus de jornadas'),
			('cambiar_estado_solicitudes', 'cambiar status de solicitudes'),
			('entregar_solicitud_medicamentos', 'Entregar solicitud de medicamentos'),
			('entregar_jornada_medicamentos', 'Entregar jornada de medicamentos'),
			('ver_inicio', 'Ver inicio'),
			('ver_mis_solicitudes_de_medicamentos', 'Ver mis solicitudes de medicamentos'),
			('ver_mis_jornada_medicamentos', 'Ver mis jornadas de medicamentos'),
			('registrar_mi_solicitud_de_medicamentos', 'Registrar mi solicitud de medicamentos'),
			('registrar_mi_jornada_medicamentos', 'Registrar mi jornada de medicamentos')
		]

	def toJSON(self):
		item = model_to_dict(self)
		if self.c_residencia:
			item['c_residencia'] = self.c_residencia.url
		else:
			item['c_residencia'] = None
		item['usuario'] = {'id': self.usuario.pk, 'username': self.usuario.username, 'is_active': self.usuario.is_active, 'email': self.usuario.email}
		item['zona'] = {'id': self.zona.pk, 'zona_residencia': self.zona.zona_residencia}
		item['genero'] = self.get_genero_display()
		return item

class Comunidad(models.Model):
	
	class Genero(models.TextChoices):
		MASCULINO = 'MA', 'Masculino'
		FEMENINO = 'FE', 'Femenino'	

	class Nacionalidad(models.TextChoices):
		VENEZOLANO = 'V-', 'V-'
		EXTRANJERO = 'E-', 'E-'
		JURIDICO = 'J-', 'J-'

	nacionalidad = models.CharField(max_length=2, choices=Nacionalidad.choices, default=Nacionalidad.VENEZOLANO, blank=False, null=False)
	cedula = models.CharField(max_length=8, blank=False, null=False)
	nombres = models.CharField(max_length=50, blank=False, null=False)
	apellidos = models.CharField(max_length=50, blank=False, null=False)
	patologia = models.TextField(blank=True, null=True)
	jefe_comunidad = models.ForeignKey(Perfil, on_delete=models.PROTECT, related_name='comunidad', blank=True, null=True)
	genero = models.CharField(max_length=2, blank=False, null=False, choices=Genero.choices, default=Genero.MASCULINO)

	def __str__(self):
		return f'{self.cedula}-{self.nombres}'
	
	class Meta:
		verbose_name = 'Comunidad'
		verbose_name_plural = 'Comunidades'

	def toJSON(self):
		item = model_to_dict(self)
		item['genero'] = self.get_genero_display()
		return item

class Beneficiado(Persona):

	class Parentesco(models.TextChoices):
		ESPOSO = 'EO', 'Esposo'
		ESPOSA = 'EA', 'Esposa'
		HIJO = 'HO', 'Hijo'
		HIJA = 'HA', 'Hija'

	perfil = models.ForeignKey(Perfil, on_delete=models.PROTECT, related_name='beneficiados')
	parentesco = models.CharField(max_length=2, blank=True, null=True, choices=Parentesco.choices)

	def __str__(self):
		return f'{self.cedula}-{self.nombres}'
		
	class Meta:
		verbose_name = 'Beneficiado'
		verbose_name_plural = 'Beneficiados'

	def toJSON(self):
		item = model_to_dict(self)
		if self.c_residencia:
			item['c_residencia'] = self.c_residencia.url
		else:
			item['c_residencia'] = None
		item['genero'] = self.get_genero_display()
		item['zona'] = {'id':self.zona.pk, 'nombre': self.zona.zona_residencia}
		return item

# personalizar landing

class LandingPage(models.Model):
	imagen1 = models.ImageField(upload_to='images_landing/', blank=True, null=True)
	imagen2 = models.ImageField(upload_to='images_landing/', blank=True, null=True)
	imagen3 = models.ImageField(upload_to='images_landing/', blank=True, null=True)
	imagen4 = models.ImageField(upload_to='images_landing/', blank=True, null=True)
	imagen5 = models.ImageField(upload_to='images_landing/', blank=True, null=True)
	texto1 = models.TextField(blank=True, null=True)

	def __str__(self) -> str:
		return super().__str__()
	
	@classmethod
	def get_config(cls):
		conf, created = cls.objects.get_or_create()
		return conf
	
	class Meta:
		verbose_name = 'Imagen'
		verbose_name_plural = 'Imagenes'

	def toJSON(self):
		item = model_to_dict(self)
		return item

apps/movimientos/models.py
from datetime import date

from django.db import models
from django.forms import model_to_dict
from django.contrib.auth.models import User

from apps.entidades.models import Beneficiado, Perfil,Comunidad
from apps.inventario.models import Producto, Inventario

# solicitud de producto
class Solicitud(models.Model):
	
	class Status(models.TextChoices):
		EN_PROCRESO = 'PR', 'En Proceso'
		DATOS_VERIFICADOS = 'DV', 'Datos Verificados'
		APROBADO = 'AP', 'Aprobado'
		EN_ESPERA_DE_ENTREGA = 'EE', 'En Espera de Entrega'
		PACIENTE_NO_RETIRO = 'NR', 'Paciente no retiró'
		ENTREGADO = 'ET', 'Entregado'
		RECHAZADO = 'RE', 'Rechazado'
	
	class TipoSoli(models.TextChoices):
		ONLINE = 'ON', 'En línea'
		PRESENCIAL = 'PR', 'Presencial'

	class FaseProceso(models.TextChoices):
		ADMINISTRADOR = 'AD', 'Administrador'
		ALMACENISTA = 'AL', 'Almacenista'
		AT_CLIENTE = 'AT', 'Atención al Cliente'
		FINALIZADO = 'FI', 'Finalizado'

	fecha_soli = models.DateField(auto_now=False, auto_now_add=False, blank=False, null=False)
	fecha_en_espera = models.DateField(auto_now=False, auto_now_add=False, blank=True, null=True)
	perfil = models.ForeignKey(Perfil, on_delete=models.PROTECT, blank=False, null=False)
	beneficiado = models.ForeignKey(Beneficiado, on_delete=models.PROTECT, blank=False, null=False)
	descripcion = models.TextField(blank=False, null=False)
	motivo_rechazo = models.TextField(blank=True, null=True)
	recipe = models.ImageField(upload_to='recipes/', blank=False, null=False)
	proceso_actual = models.CharField(max_length=2, choices= FaseProceso.choices, default=FaseProceso.AT_CLIENTE)
	estado = models.CharField(max_length=2, choices=Status.choices, default=Status.EN_PROCRESO, blank=False, null=False)
	tipo_solicitud = models.CharField(choices=TipoSoli.choices, max_length=2)

	class Meta:
		verbose_name = 'Solicitud de Medicamento'
		verbose_name_plural = 'Solicitud de Medicamentos'
		ordering = ['fecha_soli']

	def __str__(self):
		return f'{self.descripcion}'

	def toJSON(self):
		item = model_to_dict(self)
		return item

# detalle de la solicitud
class DetalleSolicitud(models.Model):
	solicitud = models.ForeignKey(Solicitud, on_delete=models.CASCADE, related_name='detalle')
	producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
	cant_solicitada = models.IntegerField(default=1)
	cant_entregada = models.IntegerField(default=0)

	class Meta:
		unique_together = ('solicitud', 'producto')  # Asegurar que no haya duplicados
		verbose_name = 'Detalle de solicitud'
		verbose_name_plural = 'Detalle de solicitudes'
		ordering = ['pk']

	def __str__(self):
		return str(self.pk)

	def toJSON(self):
		item = model_to_dict(self)
		return item
	
# detalle de invenatario solicitado
class DetalleIventarioSolicitud(models.Model):
	detsolicitud = models.ForeignKey(DetalleSolicitud, on_delete=models.CASCADE, related_name='detalle_inventario')
	inventario = models.ForeignKey(Inventario, on_delete=models.CASCADE)
	cantidad = models.IntegerField(default=0)

	class Meta:
		unique_together = ('detsolicitud', 'inventario')  # Asegurar que no haya duplicados
		verbose_name = 'Detalle de inventario solicitado'
		verbose_name_plural = 'Detalles de inventario solicitados'
		ordering = ['pk']

	def __str__(self):
		return str(self.pk)

	def toJSON(self):
		item = model_to_dict(self)
		return item

# tipo de movimiento
class TipoMov(models.Model):

	class Operacion(models.TextChoices):
		SUMA = '+', 'Suma'
		RESTA = '-', 'Resta'

	nombre = models.CharField(max_length=50)
	operacion = models.CharField(choices=Operacion.choices, max_length=2)

	class Meta:
		verbose_name = 'Tipo de Movimiento'
		verbose_name_plural = 'Tipos de Movimientos'
		ordering = ['nombre']

	def __str__(self):
		return f'{self.nombre}'

	def toJSON(self):
		item = model_to_dict(self)
		return item

class Jornada(models.Model):

	class Status(models.TextChoices):
		EN_PROCRESO = 'PR', 'En Proceso'
		APROBADO = 'AP', 'Aprobado'
		RECHAZADO = 'RE', 'Rechazado'
		ENTREGADO = 'ET', 'Entregado'

	class FaseProceso(models.TextChoices):
		ADMINISTRADOR = 'AD', 'Administrador'
		ALMACENISTA = 'AL', 'Almacenista'
		FINALIZADO = 'FI', 'Finalizado'

	encargados = models.TextField()
	descripcion = models.TextField(blank=True, null=True)
	motivo_rechazo = models.TextField(blank=True, null=True)
	fecha_solicitud = models.DateField(auto_now=False, auto_now_add=False, blank=True, null=True)
	fecha_jornada = models.DateField(auto_now=False, auto_now_add=False, blank=True, null=True)
	jefe_comunidad = models.ForeignKey(Perfil, on_delete=models.PROTECT)
	proceso_actual = models.CharField(max_length=2, choices= FaseProceso.choices, default=FaseProceso.ADMINISTRADOR)
	estado = models.CharField(max_length=2, choices=Status.choices, default=Status.EN_PROCRESO, blank=False, null=False)
	comunidad = models.ManyToManyField(Comunidad)

	class Meta:
		verbose_name = 'Jornada'
		verbose_name_plural = 'Jornadas'
		ordering = ['pk']

	def __str__(self):
		return str(self.pk)
	
	def toJSON(self):
		item = model_to_dict(self)
		return item

class DetalleJornada(models.Model):
	jornada = models.ForeignKey(Jornada, on_delete=models.CASCADE, related_name='detalle')
	producto = models.ForeignKey(Producto, on_delete=models.CASCADE, blank=True, null=True)
	cant_solicitada = models.IntegerField(default=1)
	cant_aprobada = models.IntegerField(default=0)

	class Meta:
		verbose_name = 'Detalle de Jornada'
		verbose_name_plural = 'Detalle de Jornadas'
		ordering = ['pk']

	def __str__(self):
		return str(self.pk)
	
	def toJSON(self):
		item = model_to_dict(self)
		return item

class DetalleIventarioJornada(models.Model):
	detjornada = models.ForeignKey(DetalleJornada, on_delete=models.CASCADE, related_name='detalle_inventario')
	inventario = models.ForeignKey(Inventario, on_delete=models.CASCADE)
	cantidad = models.IntegerField(default=0)

	class Meta:
		unique_together = ('detjornada', 'inventario')  # Asegurar que no haya duplicados
		verbose_name = 'Detalle de inventario jornada'
		verbose_name_plural = 'Detalles de inventario jornadas'
		ordering = ['pk']

	def __str__(self):
		return str(self.pk)

	def toJSON(self):
		item = model_to_dict(self)
		return item

# movimiento del inventario
class Historial(models.Model):
	fecha_mov = models.DateField(auto_now_add=True, blank=False, null=False)
	tipo_mov = models.ForeignKey(TipoMov, on_delete=models.PROTECT)
	empleado = models.ForeignKey(Perfil, on_delete=models.PROTECT)
	producto = models.ForeignKey(Inventario, on_delete=models.PROTECT, related_name='historial')
	cantidad = models.IntegerField(blank=False, null=False)

	def crear_movimiento(self, datos):
		movimiento = Historial()
		movimiento.tipo_mov = datos['tipo_mov']
		movimiento.empleado = datos['perfil']
		movimiento.producto = datos['producto']
		movimiento.cantidad = datos['cantidad']
		movimiento.save()

	class Meta:
		verbose_name = 'Movimiento de Inventario'
		verbose_name_plural = 'Movimientos de Inventario'
		ordering = ['-pk']

	def __str__(self):
		return str(self.pk)
	
	def toJSON(self):
		item = model_to_dict(self)
		return item
	
class Ingreso(models.Model):
	fecha = models.DateField(auto_now=False, auto_now_add=False)
	descripcion= models.TextField()
	tipo_ingreso = models.ForeignKey(TipoMov, on_delete=models.PROTECT)

	class Meta:
		verbose_name = 'Ingreso'
		verbose_name_plural = 'Ingresos'
		ordering = ['pk']

	def __str__(self):
		return str(self.pk)
	
	def toJSON(self):
		item = model_to_dict(self)
		return item
	
class DetalleIngreso(models.Model):
	ingreso = models.ForeignKey(Ingreso, on_delete=models.CASCADE, related_name='detalle')
	inventario = models.ForeignKey(Inventario, on_delete=models.PROTECT)
	cantidad = models.IntegerField()
	lote = models.CharField(max_length=50)
	f_vencimiento = models.DateField(auto_now=False, auto_now_add=False)

	class Meta:
		verbose_name = 'Detalle de ingreso'
		verbose_name_plural = 'Detalles de ingresos'

	def __str__(self):
		return str(self.pk)
	
	def toJSON(self):
		item = model_to_dict(self)
		return item

class Egreso(models.Model):
	fecha = models.DateField(auto_now=False, auto_now_add=False)
	descripcion= models.TextField()
	tipo_egreso = models.ForeignKey(TipoMov, on_delete=models.PROTECT)

	class Meta:
		verbose_name = 'Egreso'
		verbose_name_plural = 'Egresos'
		ordering = ['pk']

	def __str__(self):
		return str(self.pk)
	
	def toJSON(self):
		item = model_to_dict(self)
		return item
	
class DetalleEgreso(models.Model):
	egreso = models.ForeignKey(Egreso, on_delete=models.CASCADE, related_name='detalle')
	inventario = models.ForeignKey(Inventario, on_delete=models.PROTECT)
	cantidad = models.IntegerField()

	class Meta:
		verbose_name = 'Detalle de egreso'
		verbose_name_plural = 'Detalles de egreso'

	def __str__(self):
		return str(self.pk)
	
	def toJSON(self):
		item = model_to_dict(self)
		return item
	
class ContabilidadFisica(models.Model):

	class Status(models.TextChoices):
		EN_PROCRESO = 'PR', 'En Proceso'
		CONTABILIZADO = 'CO', 'Contabilizado'
		APROBADO = 'AP', 'Aprobado'
		RECHAZADO = 'RE', 'Rechazado'

	class FaseProceso(models.TextChoices):
		ADMINISTRADOR = 'AD', 'Administrador'
		ALMACENISTA = 'AL', 'Almacenista'
		FINALIZADO = 'FI', 'Finalizado'

	fecha = models.DateField(auto_now=False, auto_now_add=True)
	proceso_actual = models.CharField(max_length=2, choices= FaseProceso.choices, default=FaseProceso.ALMACENISTA)
	estado = models.CharField(max_length=2, choices=Status.choices, default=Status.EN_PROCRESO, blank=False, null=False)
	motivo_rechazo = models.TextField(blank=True, null=True)

	class Meta:
		verbose_name = 'Contabilidad Fisica'
		verbose_name_plural = 'Contabilidades Fisica'
		ordering = ['pk']

	def __str__(self):
		return str(self.pk)
	
	def toJSON(self):
		item = model_to_dict(self)
		return item
	
class DetContabilidadFisica(models.Model):
	contabilidad = models.ForeignKey(ContabilidadFisica, on_delete=models.CASCADE, related_name='detalle')

templates/reportes/det_solicitud.html
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{{report_title}}</title>
	<style>
		@page{
			size: a4 portrait;
			@frame logo_frame {
				-pdf-frame-content: report_header;
				left: 30pt;
				width: 110pt;
				top: 20pt;
				height: 90pt;
			}
			@frame title_frame {
				-pdf-frame-content: title_header;
				left: -450pt; width: 420pt; top: 10pt; height: 90pt;
			}
			@frame report_body {
				left: 15pt;
				width: 560pt;
				top: 90pt;
				height: 670pt;
			}
			@frame footer_frame {
				-pdf-frame-content: report_footer;
				right: 30pt;
				width: 150pt;
				top: 800pt;
				height: 20pt;
			}
            @frame emicion_frame {
				-pdf-frame-content: fecha_frame;
				left: -110pt;
				width: 100pt;
				top: 90pt;
				height: 30pt;
			}
            
		}
		.title{
			padding-top: 1.5rem;
			text-align: center;
			width: 100%;
		}
		.report_info{
			width: 100%;
			padding-top: 5rem;
		}
		.report_body{
			width: 100%;
		}
		.footer{
			text-align: right;
		}
		.head {
        text-align: center;
        text-transform: uppercase;
        font-size: 13px;
        font-weight: 600;
        margin-bottom: 3rem;
    }

        #invoice thead tr th {
            text-align: left;
            border-bottom: 1px solid black;
            border-top: 1px solid black;
            padding-top: 4px;
        }

        #invoice thead tr {
            margin-bottom: 0;
            padding-bottom: 0;
        }

        #invoice tbody tr {
            padding: 0;
        }

        .cosa{
            width: 100%;
            margin: 10px;
            border-top: black;
            font-size: 12px;
        }

        #invoice tbody tr td {
            text-align: left;
            border-bottom: 1px solid rgb(183, 183, 183);
            padding-top: 4px;
        }
	</style>
</head>

<body>

	<div class="logo" id="report_header">
		{% if logo_img %}
		    <img src="{{logo_img}}" alt="logo" width="180px" height="120px">
		{% endif %}
	</div>
	<div class="title" id="title_header">
		<p style="font-size: 14px;"
			<span>FARMACIA COMUNITARIA ASIC LEONIDAS RAMOS</span> <br>
			<span style="font-size: 12px;">URB. MANUEL CEDEÑO, ESQUINA DE LA AV.1 CON AV. 3, TAMBIÉN CONOCIDA COMO AV. RIO MEDERO.</span> <br>
		</p>
	</div>
    <div class="fecha_frame" id="fecha_frame">
        <span style="border: 1px solid black;">EMISION: {{date}}</span>
    </div>

	<div class="report_body" id="content">
		<div class="report_info" id="info">
			<p style="font-size: 12px;">
				<span style="font-weight: 700;">{{report_title|upper}}</span> <br>
			</p >
		</div>
		<table id="invoice">
			<thead>
				<tr>
					<th style="width: 30px;">ID</th>
					<th style="width: 60px;">FECHA</th>
					<th>PROCESO</th>
					<th style="width: 80px;">ESTADO</th>
					<th>DESCRIPCION</th>
					<th>TITULAR</th>
					<th>BENEFICIADO</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>{{ solicitud.pk }}</td>
					<td>{{solicitud.fecha_soli|date:'d/m/Y'}}</td>
					<td>{{solicitud.get_proceso_actual_display}}</td>
					<td>{{solicitud.get_estado_display}}</td>
					<td>{{solicitud.descripcion}}</td>
					<td>{{solicitud.perfil.cedula}}| {{solicitud.perfil.nombres}} {{solicitud.perfil.apellidos}}</td>
					<td>{{solicitud.beneficiado.cedula}}| {{solicitud.beneficiado.nombres}} {{solicitud.beneficiado.apellidos}}</td>
				</tr>
			</tbody>
		</table> <br> <br>
		<table id="invoice">
			<thead>
				<tr>
					<th>Producto</th>
					<th>Cantidad solcitada</th>
					<th>Cantidad entregada</th>
				</tr>
			</thead>
			<tbody>
				{% for det in det %}
					<tr>
						<td>{{ det.producto.nombre }}</td>
						<td>{{ det.cant_solicitada }}</td>
						{% if det.cant_entregada > 0 %}
							<td>{{ det.cant_entregada }}</td>
						{% elif solicitud.estado == 'RE' %}
								<td>Rechazado</td>
						{% else %}
							<td>En espera</td>
						{% endif %}
							
					</tr>
				{% endfor %}
			</tbody>
		</table> <br> <br>
        <br>
	</div>

	<div class="footer" id="report_footer">
		<p>Pág. <pdf:pagenumber> de <pdf:pagecount> </p>
	</div>

</body>

</html>

templates/reportes/todas_solicitudes.html
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{{report_title}}</title>
	<style>
		@page{
			size: a4 portrait;
			@frame logo_frame {
				-pdf-frame-content: report_header;
				left: 30pt;
				width: 110pt;
				top: 20pt;
				height: 90pt;
			}
			@frame title_frame {
				-pdf-frame-content: title_header;
				left: -450pt; width: 420pt; top: 10pt; height: 90pt;
			}
			@frame report_body {
				left: 15pt;
				width: 560pt;
				top: 80pt;
				height: 670pt;
			}
			@frame footer_frame {
				-pdf-frame-content: report_footer;
				right: 30pt;
				width: 150pt;
				top: 800pt;
				height: 20pt;
			}
            @frame emicion_frame {
				-pdf-frame-content: fecha_frame;
				left: -110pt;
				width: 100pt;
				top: 90pt;
				height: 30pt;
			}
            
		}
		.title{
			padding-top: 1.5rem;
			text-align: center;
			width: 100%;
		}
		.report_info{
			width: 100%;
			padding-top: 5rem;
		}
		.report_body{
			width: 100%;
		}
		.footer{
			text-align: right;
		}
		.head {
        text-align: center;
        text-transform: uppercase;
        font-size: 13px;
        font-weight: 600;
        margin-bottom: 3rem;
    }

        #invoice thead tr th {
            text-align: left;
            border-bottom: 1px solid black;
            border-top: 1px solid black;
            padding-top: 4px;
        }

        #invoice thead tr {
            margin-bottom: 0;
            padding-bottom: 0;
        }

        #invoice tbody tr {
            padding: 0;
        }

        .cosa{
            width: 100%;
            margin: 10px;
            border-top: black;
            font-size: 12px;
        }

        #invoice tbody tr td {
            text-align: left;
            border-bottom: 1px solid rgb(183, 183, 183);
            padding-top: 4px;
        }
	</style>
</head>

<body>

	<div class="logo" id="report_header">
		{% if logo_img %}
		    <img src="{{logo_img}}" alt="logo" width="180px" height="120px">
		{% endif %}
	</div>
	<div class="title" id="title_header">
		<p style="font-size: 14px;"
			<span>FARMACIA COMUNITARIA ASIC LEONIDAS RAMOS</span> <br>
			<span style="font-size: 12px;">URB. MANUEL CEDEÑO, ESQUINA DE LA AV.1 CON AV. 3, TAMBIÉN CONOCIDA COMO AV. RIO MEDERO.</span> <br>
		</p>
	</div>
    <div class="fecha_frame" id="fecha_frame">
        <span style="border: 1px solid black;">EMISION: {{date}}</span>
    </div>
	<div class="report_body" id="content">
		<div class="report_info" id="info">
			<p style="font-size: 12px;">
				<span style="font-weight: 700;">{{report_title|upper}}</span> <br>
			
			</p >
		</div>
		<table id="invoice">
			<thead>
				<tr>
					<th>PERFIL</th>
					<th>BENEFICIADO</th>
					<th>FECHA S.</th>
					<th>DESCRIPCION</th>
					<th>TIPO S.</th>
					<th>ESTADO</th>
				</tr>
			</thead>
			<tbody>
				{% for x in solicitudes %}
					<tr>
						<td class="cosa">{{ x.perfil.nacionalidad }}{{ x.perfil.cedula }}</td>
						<td class="cosa">{{ x.beneficiado.perfil.nacionalidad }}{{ x.beneficiado.perfil.cedula }}</td>
                        <td class="cosa">{{x.fecha_soli|date:'d/m/Y'}}</td>
						<td class="cosa">{{x.descripcion}}</td>
						<td class="cosa">{{x.get_tipo_solicitud_display}}</td>
                        <td class="cosa">{{x.get_estado_display}}</td></td>
					</tr>
				{% empty %}
					<tr>
						<td colspan="6" valign="middle" class="cosa">SIN REGISTROS</td>
					</tr>
				{% endfor %}
			</tbody>
		</table> <br> <br>
        <br>
	</div>

	<div class="footer" id="report_footer">
		<p>Pág. <pdf:pagenumber> de <pdf:pagecount> </p>
	</div>

</body>

</html>