CONFIG/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.inventario.urls')),
    path('', include('apps.entidades.urls')),
    path('', include('apps.movimientos.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/entidades/urls.py
from django.urls import path
from .views import (
    Inicio, 
    landing, 
    RegistrarPerfil, 
    ListadoPerfiles, 
    LoginPersonalidado, 
    ListaZona, 
    RegistrarZona, 
    ActualizarZona,
    Logout,
    CambiarClave,
    ActualizarLanding,
    ResetPassword,
    DetallesUsuario,
    EditarUsuario,
    ListadoMicomunidad,
    RegistrarComunidad,
    EditarComunidad,
    EliminarComunidad,
    MiPerfil, 
    ActualizarInfo,
    MenuReportes
)

from .reportes import (
    TodosPerfiles,
    TodosBeneficiados
)

urlpatterns = [
    path('inicio/', Inicio.as_view(), name='vista'),
    path('', landing.as_view()),
    path('actualizar-landing/', ActualizarLanding.as_view(), name='edit_landing'),
    path('menu-de-reportes/', MenuReportes.as_view(), name='reportes'),

    # perfil de usuario
    path('mi-perfil/', MiPerfil.as_view(), name='perfil'),
    path('actualizar-mi-informacion/', ActualizarInfo.as_view(), name='edit_info'),

    path('registrar-perfil/', RegistrarPerfil.as_view(), name='new_perfil'),
    path('listado-de-perfiles/', ListadoPerfiles.as_view(), name='lista_perfiles'),
    path('detalle-de-perfil/<int:pk>/', DetallesUsuario.as_view(), name='detalle_perfiles'),
    path('editar-perfil/<int:pk>/', EditarUsuario.as_view(), name='editar_perfil'),

    # mi comuniad    
    path('listado-de-mi-comunidad/', ListadoMicomunidad.as_view(), name='listado_mi_comunidad'),
    path('registrar-beneficiado-jornada/', RegistrarComunidad.as_view(), name='registrar_beneficiado_jornada'),
    path('editar-beneficiado/<int:pk>/', EditarComunidad.as_view(), name='editar_comunidad'),
    path('eliminar-beneficiado/<int:pk>/', EliminarComunidad.as_view(), name='eliminar_comunidad'),

    # control de acceso
    path('ingresar/', LoginPersonalidado.as_view(), name='login'),
    path('cerrar-sesion/', Logout.as_view(), name='logout'),
    path('actualizar-clave/', CambiarClave.as_view(), name='cambiar_clave'),
    path('reset-password/', ResetPassword.as_view(), name='reset_pass'),

    path('listado-de-zonas/', ListaZona.as_view(), name='lista_zonas'),
    path('registro-de-zona/', RegistrarZona.as_view(), name='nueva_zona'),
    path('actualizar-zona/', ActualizarZona.as_view(), name='actualizar_zona'),

    # reportes
    path('reportes/todos-los-perfiles/', TodosPerfiles.as_view(), name='t_perfiles'),
    path('reportes/todos-los-beneficiados/', TodosBeneficiados.as_view(), name='t_beneficiados'),
]

apps/entidades/models.py
from django.db import models
from django.forms import model_to_dict
from django.contrib.auth.models import User

# zona
class Zona(models.Model):
	zona_residencia = models.CharField(max_length=60, blank=False, null=False)

	class Meta:
		verbose_name = 'Zona'
		verbose_name_plural = 'Zonas'

	def __str__(self):
		return self.zona_residencia

	def toJSON(self):
		item = model_to_dict(self)
		return item

class Persona(models.Model):

	class Genero(models.TextChoices):
		MASCULINO = 'MA', 'Masculino'
		FEMENINO = 'FE', 'Femenino'

	class Nacionalidad(models.TextChoices):
		VENEZOLANO = 'V-', 'V-'
		EXTRANJERO = 'E-', 'E-'
		JURIDICO = 'J-', 'J-'
	
	class CodigoTlf(models.TextChoices):
		C412 = '0412', '0412'
		C414 = '0414', '0414'
		C416 = '0416', '0416'
		C424 = '0424', '0424'
		C426 = '0426', '0426'

	nacionalidad = models.CharField(max_length=2, choices=Nacionalidad.choices, default=Nacionalidad.VENEZOLANO, blank=False, null=False)
	cedula = models.CharField(max_length=8, blank=False, null=False)
	nombres = models.CharField(max_length=50, blank=False, null=False)
	apellidos = models.CharField(max_length=50, blank=False, null=False)
	telefono = models.CharField(max_length=11, blank=True, null=True)
	genero = models.CharField(max_length=2, blank=False, null=False, choices=Genero.choices)
	f_nacimiento = models.DateField(auto_now_add = False, auto_now=False, blank=False, null=False)
	embarazada = models.BooleanField(blank=False, null=False)
	c_residencia = models.FileField(upload_to='constancias_residencias/', blank=True, null=True)
	zona  = models.ForeignKey(Zona, on_delete=models.PROTECT, blank=False, null=False)
	direccion = models.TextField(blank=False, null=False)
	patologia = models.TextField(blank=True, null=True)

	class Meta:
		abstract = True

	def toJSON(self):
		item = model_to_dict(self)
		if self.c_residencia:
			item['c_residencia'] = self.c_residencia.url
		else:
			item['c_residencia'] = None
		return item

class Perfil(Persona):
	class Rol(models.TextChoices):
		ADMINISTRADOR = 'AD', 'Administrador'
		ALMACENISTA = 'AL', 'Almacenista'
		AT_CLIENTE = 'AT', 'Atención al Cliente'
		JEFE_COMUNIDAD = 'JC', 'Jefe de Comunidad'
		PACIENTE = 'PA', 'Paciente'
	
	rol = models.CharField(max_length=2, choices=Rol.choices, default=Rol.PACIENTE)
	usuario = models.OneToOneField(User, on_delete=models.CASCADE, related_name='perfil')
	
	def __str__(self):
		return f'{self.cedula}-{self.nombres}'
	
	class Meta:
		verbose_name = 'perfil'
		verbose_name_plural = 'perfiles'
		permissions = [
			('cambiar_password', 'cambiar contraseña a usuarios'),
			('respaldar_db', 'Respaldar Base de datos'),
			('recuperar_db', 'Recuperar Base de datos'),
			('cambiar_estado_usuarios', 'cambiar estado de usuarios'),
			('cambiar_estado_jornada', 'cambiar estatus de jornadas'),
			('cambiar_estado_solicitudes', 'cambiar status de solicitudes'),
			('entregar_solicitud_medicamentos', 'Entregar solicitud de medicamentos'),
			('entregar_jornada_medicamentos', 'Entregar jornada de medicamentos'),
			('ver_inicio', 'Ver inicio'),
			('ver_mis_solicitudes_de_medicamentos', 'Ver mis solicitudes de medicamentos'),
			('ver_mis_jornada_medicamentos', 'Ver mis jornadas de medicamentos'),
			('registrar_mi_solicitud_de_medicamentos', 'Registrar mi solicitud de medicamentos'),
			('registrar_mi_jornada_medicamentos', 'Registrar mi jornada de medicamentos')
		]

	def toJSON(self):
		item = model_to_dict(self)
		if self.c_residencia:
			item['c_residencia'] = self.c_residencia.url
		else:
			item['c_residencia'] = None
		item['usuario'] = {'id': self.usuario.pk, 'username': self.usuario.username, 'is_active': self.usuario.is_active, 'email': self.usuario.email}
		item['zona'] = {'id': self.zona.pk, 'zona_residencia': self.zona.zona_residencia}
		item['genero'] = self.get_genero_display()
		return item

class Comunidad(models.Model):
	
	class Genero(models.TextChoices):
		MASCULINO = 'MA', 'Masculino'
		FEMENINO = 'FE', 'Femenino'	

	class Nacionalidad(models.TextChoices):
		VENEZOLANO = 'V-', 'V-'
		EXTRANJERO = 'E-', 'E-'
		JURIDICO = 'J-', 'J-'

	nacionalidad = models.CharField(max_length=2, choices=Nacionalidad.choices, default=Nacionalidad.VENEZOLANO, blank=False, null=False)
	cedula = models.CharField(max_length=8, blank=False, null=False)
	nombres = models.CharField(max_length=50, blank=False, null=False)
	apellidos = models.CharField(max_length=50, blank=False, null=False)
	patologia = models.TextField(blank=True, null=True)
	jefe_comunidad = models.ForeignKey(Perfil, on_delete=models.PROTECT, related_name='comunidad', blank=True, null=True)
	genero = models.CharField(max_length=2, blank=False, null=False, choices=Genero.choices, default=Genero.MASCULINO)

	def __str__(self):
		return f'{self.cedula}-{self.nombres}'
	
	class Meta:
		verbose_name = 'Comunidad'
		verbose_name_plural = 'Comunidades'

	def toJSON(self):
		item = model_to_dict(self)
		item['genero'] = self.get_genero_display()
		return item

class Beneficiado(Persona):

	class Parentesco(models.TextChoices):
		ESPOSO = 'EO', 'Esposo'
		ESPOSA = 'EA', 'Esposa'
		HIJO = 'HO', 'Hijo'
		HIJA = 'HA', 'Hija'

	perfil = models.ForeignKey(Perfil, on_delete=models.PROTECT, related_name='beneficiados')
	parentesco = models.CharField(max_length=2, blank=True, null=True, choices=Parentesco.choices)

	def __str__(self):
		return f'{self.cedula}-{self.nombres}'
		
	class Meta:
		verbose_name = 'Beneficiado'
		verbose_name_plural = 'Beneficiados'

	def toJSON(self):
		item = model_to_dict(self)
		if self.c_residencia:
			item['c_residencia'] = self.c_residencia.url
		else:
			item['c_residencia'] = None
		item['genero'] = self.get_genero_display()
		item['zona'] = {'id':self.zona.pk, 'nombre': self.zona.zona_residencia}
		return item

# personalizar landing

class LandingPage(models.Model):
	imagen1 = models.ImageField(upload_to='images_landing/', blank=True, null=True)
	imagen2 = models.ImageField(upload_to='images_landing/', blank=True, null=True)
	imagen3 = models.ImageField(upload_to='images_landing/', blank=True, null=True)
	imagen4 = models.ImageField(upload_to='images_landing/', blank=True, null=True)
	imagen5 = models.ImageField(upload_to='images_landing/', blank=True, null=True)
	texto1 = models.TextField(blank=True, null=True)

	def __str__(self) -> str:
		return super().__str__()
	
	@classmethod
	def get_config(cls):
		conf, created = cls.objects.get_or_create()
		return conf
	
	class Meta:
		verbose_name = 'Imagen'
		verbose_name_plural = 'Imagenes'

	def toJSON(self):
		item = model_to_dict(self)
		return item

apps/entidades/forms.py
from django import forms
from .models import Perfil, Zona, LandingPage, Comunidad, Beneficiado

class FormComunidad(forms.ModelForm):
	class Meta:
		model = Comunidad
		fields = '__all__'

class PerfilForm(forms.ModelForm):

	password1 = forms.CharField(label='Contrasena', widget=forms.PasswordInput)
	password2 = forms.CharField(label='Confirme Contrasena', widget=forms.PasswordInput)
	email = forms.EmailField(label = 'Correo', widget=forms.EmailInput)
	codigo_tlf = forms.ChoiceField(choices=Perfil.CodigoTlf.choices)
	class Meta:
		model = Perfil
		fields = ['nacionalidad', 'cedula', 'nombres', 'apellidos', 'telefono', 'genero', 'f_nacimiento', 'embarazada', 'c_residencia', 'zona', 'direccion', 'rol', 'patologia']

	def clean_password2(self):
		# Check that the two password entries match
		password1 = self.cleaned_data.get("password1")
		password2 = self.cleaned_data.get("password2")
		if password1 and password2 and password1 != password2:
			raise forms.ValidationError("Las contrasena no coinciden")
		return password2

class ZonaForm(forms.ModelForm):
	class Meta:
		model = Zona
		fields = '__all__'

class FormLanding(forms.ModelForm):
	class Meta:
		model = LandingPage
		fields = '__all__'

class FormEditPerfil(forms.ModelForm):
	email = forms.EmailField(label = 'Correo', widget=forms.EmailInput)
	class Meta:
		model = Perfil
		fields = '__all__'
		exclude = ['nacionalidad', 'cedula', 'usuario']

class BeneficiadoForm(forms.ModelForm):
	class Meta:
		model = Beneficiado
		fields = '__all__'

templates/pages/entidades/detalle_usuario.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}
    Detalle de Usuario
{% endblock title %}

{% block extra_css %}    	
    <!--Data table-->
    <link rel="stylesheet" href="{% static 'css/buttons.bootstrap5.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/dataTables.bootstrap5.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.bootstrap5.min.css' %}">
{% endblock extra_css %}

{% block body %}
    <div class="row">
        <div class="col col-md-12">
            <div class="card">
                <div class="card-header">
                    <strong class="card-title">Datos personales</strong>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col col-md-4">
                            <h4 class="card-title">ID</h4>
                            <p class="card-text">{{ perfil.pk }}.</p>
        
                        </div>
                        <div class="col col-md-4">
                            <h4 class="card-title">Cedula</h4>
                            <p class="card-text">{{perfil.nacionalidad}}{{perfil.cedula}}</p>
                        </div>
                        <div class="col col-md-4">
                            <h4 class="card-title">Nombres y Apellidos</h4>
                            <p class="card-text">{{perfil.nombres}} {{perfil.apellidos}}.</p>
                        </div>
                        
                    </div>
                    <div class="row mt-4">
                        <div class="col col-md-4">
                            <h4 class="card-title">Telefono</h4>
                            <p class="card-text">{{perfil.telefono}}.</p>
                        </div>
                        <div class="col col-md-4">
                            <h4 class="card-title">Genero</h4>
                            <p class="card-text">{{perfil.get_genero_display}}.</p>
                        </div>
                        <div class="col col-md-4">
                            <h4 class="card-title">F. nacimiento</h4>
                            <p class="card-text">{{perfil.f_nacimiento|date:'d/m/Y'}}.</p>
                        </div>
                    </div>

                    <div class="row mt-4">
                        <div class="col col-md-4">
                            <h4 class="card-title">Embarazada?</h4>
                            {% if perfil.genero == 'MA' %}
                                <p class="card-text">No aplica.</p>
                            {% else %}
                            <p class="card-text">{{perfil.embarazada|yesno:'Si,No'}}.</p>
                            {% endif %}
                        </div>
                        <div class="col col-md-4">
                            <h4 class="card-title">Constancia de R.</h4>
                            {% if perfil.c_residencia %}
                                <a href="{{perfil.c_residencia.url}}" target="_blank">Ver constancia</a>
                            {% else %}
                                <p class="card-text">NO ASIGNADO.</p>
                            {% endif %}
                        </div>
                        <div class="col col-md-4">
                            <h4 class="card-title">Zona</h4>
                            <p class="card-text">{{perfil.zona}}.</p>
                        </div>
                    </div>

                    <div class="row mt-4">
                        <div class="col">
                            <h4 class="card-title">Direccion.</h4>
                            <p class="card-text">{{perfil.direccion}}.</p>
                        </div>
                        <div class="col">
                            <h4 class="card-title">Rol en el Sistema.</h4>
                            <p class="card-text">{{perfil.get_rol_display}}.</p>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col col-md-12">
            <div class="card">
                <div class="card-header">
                    <strong class="card-title">Beneficiados del Perfil</strong>
                </div>
                <div class="card-body">
                    <div class="dt-responsive table-responsive">
                        <table id="listado" class="table table-striped table-hover table-bordered nowrap">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Cedula</th>
                                    <th>Nombres</th>
                                    <th>Genero</th>
                                    <th>F. Nac.</th>
                                    <th>Embarazo</th>
                                  </tr>
                            </thead>
                            <tbody>
                                {% for x in beneficiado %}
                                    <tr>
                                        <td>{{ x.id }}</td>
                                        <td>{{ x.nacionalidad }}{{x.cedula}}</td>
                                        <td>{{ x.nombres}} {{x.apellidos}}</td>
                                        <td>{{ x.get_genero_display }}</td>
                                        <td>{{ x.f_nacimiento|date:'d/m/Y' }}</td>
                                        {% if x.genero == 'MA' %}
                                            <td>NO APLICA</td>
                                        {% else %}
                                            <td>{{ x.embarazada|yesno:'Si,No' }}</td>
                                        {% endif %}
                                    </tr>
                                {% endfor %}
                                    

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock body %}

{% block extrajs %}
	<!--Data table-->
	<script src="{% static 'js/plugins/jquery.dataTables.min.js' %}"></script>
	<script src="{% static 'js/plugins/dataTables.bootstrap5.min.js' %}"></script>
	<script src="{% static 'js/plugins/dataTables.responsive.min.js' %}"></script>
	<script src="{% static 'js/plugins/responsive.bootstrap5.min.js' %}"></script>     

{% endblock extrajs %}

templates/pages/entidades/editar_usuarios.html
{% extends 'base/base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}
    Listado de Usuarios
{% endblock title %}

{% block extra_css %}
    	<!--Data table-->
	<link rel="stylesheet" href="{% static 'css/buttons.bootstrap5.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/dataTables.bootstrap5.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/responsive.bootstrap5.min.css' %}">
{% endblock extra_css %}
    

{% block body %}
<form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
    <div class="card">
        {% if messages %}
            {% for message in messages %}
                <div class="sufee-alert alert with-close alert-success alert-dismissible fade show">
                    <span class="badge badge-pill badge-success">Exito!</span>
                    {{ message }}.
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
            {% endfor %}
        {% endif %}
        <div class="card-header">
            <strong class="card-title">Edición de Usuarios</strong>
        </div>
        <div class="card-body">

            <div class="row g-2 mb-3">
                <div class="col">
                    <label for="">Nombres</label>
                    {{form.nombres|add_class:'form-control'|attr:'required'|attr:'onkeypress:return Solo_Texto(event)'}}
                </div>
                <div class="col">
                    <label for="">Apellidos</label>
                    {{form.apellidos|add_class:'form-control'|attr:'required'|attr:'onkeypress:return Solo_Texto(event)'}}
                </div>
            </div>
            <div class="row g-2 mb-3">
                <div class="col">
                    <label for="">Fecha de nacimiento</label>
                    <input type="date" name="f_nacimiento" value="{{ form.f_nacimiento.value|date:'Y-m-d' }}" class="form-control" required>

                </div>
                <div class="col">
                    <label for="">Genero</label>
                    {{form.genero|add_class:'form-control'|attr:'required'}}
                </div>
            </div>

            <div class="row g-2 mb-3">
                <div class="col">
                    <label for="">¿Esta embarazada?</label>
                    {{form.embarazada|add_class:'form-control'}}
                </div>
                <div class="col">
                    <label for="">Telefono</label>
                    {{form.telefono|add_class:'form-control'|attr:'required'|attr:'onkeypress:return Solo_Numero(event)'|attr:'maxlength:11'|attr:'minlength:11'}}
                </div>
            </div>

            <div class="row g-2 mb-3">
                <div class="col">
                    <label for="">Zona</label>
                    {{form.zona|add_class:'form-control'|attr:'required'}}
                </div>
                <div class="col">
                    <label for="">Constancia de residencia</label>
                    {{form.c_residencia|add_class:'form-control-file'}}
                </div>
            </div>

            <div class="row mb-3">
                <div class="col">
                    <label for="">Rol en el sistema</label>
                    {{form.rol|add_class:'form-control'|attr:'required'}}
                </div>
                <div class="col">
                    <label for="">Correo</label>
                    {{form.email|add_class:'form-control'|attr:'required'}}
                </div>
            </div>

            <div class="row">
                <div class="col">
                    <label for="">Patología</label>
                    {{form.patologia|add_class:'form-control'|attr:'rows:5'|attr:'style:resize:none'|attr:'required'|attr:'onkeypress:return Texto_Numeros(event)'}}
                </div>
                <div class="col">
                    <label for="">Direccion</label>
                    {{form.direccion|add_class:'form-control'|attr:'rows:5'|attr:'style:resize:none'|attr:'required'|attr:'onkeypress:return Texto_Numeros(event)'}}
                </div>
            </div>
        </div>

        <div class="card-footer">
            <input type="submit" value="Guardar" class="btn btn-primary">
            <a href="{% url 'lista_perfiles' %}" class="btn btn-danger">Cancelar</a>
        </div>
    </div>
</form>

{% endblock body %}


{% block extrajs %}
    <!--Data table-->
    <script src="{% static 'js/plugins/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'js/plugins/dataTables.bootstrap5.min.js' %}"></script>
    <script src="{% static 'js/plugins/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'js/plugins/responsive.bootstrap5.min.js' %}"></script>

    <script src="{% static 'js/pages/entidades/usuarios.js' %}"></script>

    <script>
        $(document).ready(function() {
            // Asume que los campos tienen los IDs 'id_genero' y 'id_embarazada'
            $('#id_genero').change(function() {
                var genero = $(this).val();
                if (genero === 'MA') {
                    // Si el género es masculino, establece el campo embarazada en False
                    $('#id_embarazada').prop('checked', false);
                    // Opcionalmente, deshabilita el campo embarazada
                    $('#id_embarazada').prop('disabled', true);
                } else if (genero === 'FE') {
                    // Si el género es femenino, habilita el campo embarazada
                    $('#id_embarazada').prop('disabled', false);
                }
            });
            // Trigger change para establecer el estado inicial correcto
            $('#id_genero').trigger('change');
        });
        </script>
{% endblock extrajs %}
    

templates/pages/entidades/modal_reset_pass.html
<!-- modales -->
<div class="modal fade" id="modal_reset_password" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="smallmodalLabel" aria-hidden="true">
    <div class="modal-dialog " role="document">
        <form action="" method="post" id="form_reset_password">{% csrf_token %}
            <input type="hidden" name="action_reset" value="" id="id_action_reset">
            <input type="hidden" name="id_reset" value="">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="smallmodalLabel">Recuperar contraseña</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="modal-body">
                        <div class="row mb-3">
                            <label for="id_username_reset">Usuario</label>
                            <input type="text" name="username_reset" id="id_username_reset" class="form-control" required readonly>
                        </div>
                        <div class="row g-2">
                            <div class="col">
                                <label for="">Contraseña</label>
                                <input type="password" onkeypress="return Texto_Numeros(event)" minlength="6" name="password1_reset" id="id_password1_reset" class="form-control" required>
                            </div>
                            <div class="col">
                                <label for="">Confirme contraseña</label>
                                <input type="password" onkeypress="return Texto_Numeros(event)" minlength="6" name="password2_reset" id="id_password2_reset" class="form-control" required>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-primary">Confirmar</button>
                </div>
            </div>
        </form>
    </div>
</div>